---
abstract: 'Mix & match Source engine game mods'
author:
  - 'Marius Gavrilescu <marius@ieval.ro>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-Web-VPKBuilder
no_index:
  directory:
    - t
    - inc
requires:
  Data::Diver: '0'
  File::Basename: '0'
  File::Find: '0'
  File::Path: '0'
  File::Slurp: '0'
  File::Spec::Functions: '0'
  File::Temp: '0'
  HTML::Element: '0'
  HTML::TreeBuilder: '0'
  Hash::Merge: '0'
  IO::Compress::Zip: '0'
  List::MoreUtils: '0'
  Plack::Builder: '0'
  Plack::Component: '0'
  Plack::Request: '0'
  Sort::ByExample: '0'
  YAML: '0'
  perl: '5.014000'
  sigtrap: '0'
resources:
  repository: http://git.ieval.ro/?p=app-web-vpkbuilder.git
version: 0.000_001
